services:
  - type: web
    name: sacredheart
    buildCommand: cd $PWD && yarn install && yarn build
    startCommand: yarn server
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20

